worker_processes 4;

events {
  worker_connections 1024;
}

http {
    upstream bwg-service {
        server bwg:5000;
    }

    server {
        listen 80;

        location /api {
            proxy_pass http://bwg-service;
        }

    }
}